services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: single
    env_file: .env.docker
    environment:
      INTERNAL_DB: 1
      DB_HOST: 127.0.0.1
      DB_PASSWORD: ${DB_PASSWORD:-change_me}
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./bind/storage
        target: /var/www/html/storage
      - type: bind
        source: ./bind/mysql
        target: /var/lib/mysql
    restart: unless-stopped
